CREATE TABLE MEMBER_GRADE_POLICY
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고객 등급 ID',

    -- 데이터
    GRADE_NAME         VARCHAR(50)  NOT NULL COMMENT '고객 등급 이름',
    MIN_AMOUNT         INT          NOT NULL COMMENT '최소 구매 금액',
    MAX_AMOUNT         INT          NOT NULL COMMENT '최대 구매 금액',
    PERIOD_DAYS        INT          NOT NULL COMMENT '등급 기준 기간(일)',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '고객 등급 설명',
    CONSTRAINT CHK_MIN_LESS_THAN_MAX CHECK (MIN_AMOUNT <= MAX_AMOUNT),

    --  시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

CREATE TABLE MEMBER_GRADE_POLICY_HISTORY
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고객 등급 이력 ID (기본 키)',

    -- 외래키
    GRADE_ID             BIGINT       NOT NULL COMMENT '원래 고객 등급 ID',
    CONSTRAINT FK_MEMBER_GRADE_POLICY_HISTORY_GRADE
        FOREIGN KEY (GRADE_ID) REFERENCES MEMBER_GRADE_POLICY (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    GRADE_NAME           VARCHAR(50)  NOT NULL COMMENT '고객 등급 이름(이전 데이터)',
    MIN_AMOUNT           INT          NOT NULL COMMENT '최소 구매 금액(이전 데이터)',
    MAX_AMOUNT           INT          NOT NULL COMMENT '최대 구매 금액(이전 데이터)',
    PERIOD_DAYS          INT          NOT NULL COMMENT '고객 등급 기간(이전 데이터)',
    DESCRIPTION          VARCHAR(255) NULL COMMENT '고객 등급 설명(이전 데이터)',
    CREATED_DATE         DATETIME(6)  NULL COMMENT '고객 등급 생성 날짜(이전 데이터)',
    LAST_MODIFIED_DATE   DATETIME(6)  NULL COMMENT '고객 등급 수정 날짜(이전 데이터)',
    DELETED_DATE         DATETIME(6)  NULL COMMENT '고객 등급 삭제 날짜(이전 데이터)',

    -- 시스템 컬럼
    OPERATION_TYPE       VARCHAR(10)  NOT NULL COMMENT '조작 유형(UPDATE/DELETE)',
    HISTORY_CREATED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '이력 생성 날짜'

);

CREATE TABLE MEMBER
(
    -- 기본키
    ID                    BIGINT       NOT NULL PRIMARY KEY COMMENT '회원 ID (기본 키)',

    -- 외래키
    GRADE_ID              BIGINT       NULL COMMENT '고객 등급 ID (외래 키)',
    CONSTRAINT FK_MEMBER_GRADE_POLICY FOREIGN KEY (GRADE_ID) REFERENCES MEMBER_GRADE_POLICY (ID),

    -- 데이터
    NAME                  VARCHAR(255) NOT NULL COMMENT '회원 이름',
    SEX                   CHAR(1)      NOT NULL COMMENT '성별',
    BIRTHDATE             DATE         NOT NULL COMMENT '생년월일',
    EMAIL                 VARCHAR(255) NOT NULL UNIQUE COMMENT '회원 이메일',
    PASSWORD              VARCHAR(255) NOT NULL COMMENT '비밀번호',
    ADDRESS               VARCHAR(255) NULL COMMENT '주소',
    ADDRESS_LINE          VARCHAR(255) NULL COMMENT '상세주소',
    ADDRESS_ZIP_CODE      VARCHAR(255) NULL COMMENT '우편번호',
    MOBILE                VARCHAR(255) NOT NULL COMMENT '휴대폰 번호',
    LANDLINE              VARCHAR(255) NULL COMMENT '전화번호',
    CURRENT_POINTS        INT          NOT NULL DEFAULT 0 COMMENT '현재 보유 포인트',
    TOTAL_EARNED_POINTS   INT          NOT NULL DEFAULT 0 COMMENT '총 얻은 포인트',
    TOTAL_REDEEMED_POINTS INT          NOT NULL DEFAULT 0 COMMENT '총 사용한 포인트',
    MEMBER_STATUS         VARCHAR(255) NOT NULL COMMENT '회원 상태',
    LATEST_LOGIN_DATE     DATETIME     NULL COMMENT '마지막 로그인 날짜',
    REG_DATE              DATETIME(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '회원가입 날짜',
    CHECK (SEX IN ('M', 'F', 'O')),

    -- 시스템 컬럼
    CREATED_DATE          DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE    DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE          DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜'
);

CREATE TABLE DELIVERY_ADDRESS
(
    -- 기본키
    ID                        BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '배송지 주소 ID (기본 키)',

    -- 외래키
    MEMBER_ID                 BIGINT       NOT NULL COMMENT '회원 ID (외래 키)',
    CONSTRAINT FK_DELIVERY_ADDRESS_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT ,

    -- 데이터
    DELIVERY_ADDRESS          VARCHAR(255) NOT NULL COMMENT '배송지 주소',
    DELIVERY_ADDRESS_LINE     VARCHAR(255) NOT NULL COMMENT '배송지 상세주소',
    DELIVERY_ADDRESS_ZIP_CODE INT          NOT NULL COMMENT '배송지 우편번호',
    ADDRESS_TYPE              VARCHAR(255) NOT NULL COMMENT '주소 별명',
    IS_PRIMARY_ADDRESS        BOOLEAN      NOT NULL COMMENT '기본배송지 여부',
    IS_LATEST_ADDRESS         BOOLEAN      NOT NULL COMMENT '최근배송지 여부',

    -- 시스템 컬럼
    CREATED_DATE              DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE        DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE              DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

CREATE TABLE MEMBER_HISTORY
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '멤버 이력 ID (기본 키)',

    -- 외래키
    MEMBER_ID            BIGINT       NOT NULL COMMENT '이력 대상 회원 ID',
    CONSTRAINT FK_MEMBER_HISTORY_MEMBER
        FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    NAME                 VARCHAR(255) NOT NULL COMMENT '회원 이름(이전 데이터)',
    EMAIL                VARCHAR(255) NOT NULL COMMENT '회원 이메일(이전 데이터)',
    PASSWORD             VARCHAR(255) NOT NULL COMMENT '비밀번호(이전 데이터)',
    ADDRESS              VARCHAR(255) NULL COMMENT '주소(이전 데이터)',
    MOBILE               VARCHAR(255) NULL COMMENT '휴대폰(이전 데이터)',
    GRADE_ID             BIGINT       NULL COMMENT '등급 ID(이전 데이터)',
    CREATED_DATE         DATETIME(6)  NULL COMMENT '회원 생성 날짜(이전 데이터)',
    LAST_MODIFIED_DATE   DATETIME(6)  NULL COMMENT '회원 수정 날짜(이전 데이터)',
    DELETED_DATE         DATETIME(6)  NULL COMMENT '회원 삭제 날짜(이전 데이터)',

    -- 시스템 컬럼
    OPERATION_TYPE       VARCHAR(10)  NOT NULL COMMENT '조작 유형(UPDATE/DELETE)',
    HISTORY_CREATED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '이력 생성 날짜'

);



-- 퍼센테이지 기반 포인트 정책 테이블 (상위 정책 정의)
CREATE TABLE PERCENTAGE_POINT_POLICY
(
    ID                     BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '퍼센트 기반 포인트 정책 ID (기본 키)',
    MEMBER_GRADE_POLICY_ID BIGINT       NOT NULL COMMENT '고객 등급 ID (외래 키)',
    DESCRIPTION            VARCHAR(255) NULL COMMENT '퍼센트 기반 포인트 정책 설명',
    ACTIVATED              BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '퍼센트 기반 포인트 정책 활성화 여부',
    CREATED_DATE           DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE     DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE           DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_PERCENTAGE_POINT_POLICY_GRADE FOREIGN KEY (MEMBER_GRADE_POLICY_ID) REFERENCES MEMBER_GRADE_POLICY (ID)
);

-- 퍼센테이지 포인트 액/비율 관리 테이블 (기간, 비율을 여기에 관리)
CREATE TABLE PERCENTAGE_POINT_POLICY_DETAIL
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '퍼센트 포인트 비율 관리 ID (기본 키)',
    PERCENTAGE_POLICY_ID BIGINT        NOT NULL COMMENT '퍼센트 기반 포인트 정책 ID (외래 키)',
    PERCENTAGE           DECIMAL(5, 2) NOT NULL COMMENT '적립률(%)',
    EFFECTIVE_START_DATE DATETIME(6)   NOT NULL COMMENT '퍼센트 기반 포인트 정책 유효 시작 날짜',
    EFFECTIVE_END_DATE   DATETIME(6) DEFAULT NULL COMMENT '퍼센트 기반 포인트 정책 유효 종료 날짜',
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_PERCENTAGE_POINT_POLICY_DETAIL FOREIGN KEY (PERCENTAGE_POLICY_ID) REFERENCES PERCENTAGE_POINT_POLICY (ID)
);

-- 고정 포인트 정책 테이블 (상위 정책 정의)
CREATE TABLE FIXED_POINT_POLICY
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고정 포인트 정책 ID (기본 키)',
    POLICY_NAME        VARCHAR(50)  NOT NULL UNIQUE COMMENT '고정 포인트 정책 이름',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '고정 포인트 정책 설명',
    ACTIVATED          BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '고정 포인트 정책 활성화 여부',
    CREATED_DATE       DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜'
);

-- 고정 포인트 액 관리 테이블 (기간, 액수를 여기에 관리)
CREATE TABLE FIXED_POINT_POLICY_DETAIL
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고정 포인트 액 관리 ID (기본 키)',
    FIXED_POLICY_ID      BIGINT      NOT NULL COMMENT '고정 포인트 정책 ID (외래 키)',
    POINT_AMOUNT         INT         NOT NULL COMMENT '지급 포인트 액',
    EFFECTIVE_START_DATE DATETIME(6) NOT NULL COMMENT '고정 포인트 정책 유효 시작 날짜(이벤트 기간 시작)',
    EFFECTIVE_END_DATE   DATETIME(6) DEFAULT NULL COMMENT '고정 포인트 정책 유효 종료 날짜(이벤트 기간 종료)',
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_FIXED_POINT_POLICY_DETAIL_POLICY FOREIGN KEY (FIXED_POLICY_ID) REFERENCES FIXED_POINT_POLICY (ID)
);


-- 약관 메인 테이블 (약관 종류 정의)
CREATE TABLE TERMS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '약관 ID (기본 키)',
    NAME               VARCHAR(100) NOT NULL UNIQUE COMMENT '약관 이름 (예: 이용약관, 개인정보처리방침 등)',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '약관 설명',
    REQUIRED           BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '필수 동의 여부',
    ACTIVATED          BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '약관 활성화 여부'
    #     CREATED_DATE       DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    #     LAST_MODIFIED_DATE DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    #     DELETED_DATE       DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜'
);

-- 약관 버전 관리 테이블 (메인 약관의 버전별 내용)
CREATE TABLE TERMS_VERSION
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '약관 버전 ID (기본 키)',

    TERMS_ID             BIGINT      NOT NULL COMMENT '약관 ID (외래 키)',
    VERSION_NO           INT         NOT NULL COMMENT '약관 버전 번호',
    CONTENT              TEXT        NOT NULL COMMENT '약관 내용',
    EFFECTIVE_START_DATE DATETIME(6) NOT NULL COMMENT '약관 유효 시작 날짜',
    EFFECTIVE_END_DATE   DATETIME(6) DEFAULT NULL COMMENT '약관 유효 종료 날짜',
    #     CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    #     LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    #     DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_TERMS_VERSION_TERMS FOREIGN KEY (TERMS_ID) REFERENCES TERMS (ID)
);

-- 서브 약관 테이블 (메인 약관 하위에 속하는 세부 약관 정의)
CREATE TABLE SUB_TERMS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '서브 약관 ID (기본 키)',
    TERMS_ID           BIGINT       NOT NULL COMMENT '메인 약관 ID (외래 키)',
    NAME               VARCHAR(100) NOT NULL COMMENT '서브 약관 이름 (예: 개인정보 이용동의, 위치정보 이용동의 등)',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '서브 약관 설명',
    REQUIRED           BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '필수 동의 여부',
    ACTIVATED          BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '약관 활성화 여부',
    #     CREATED_DATE       DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    #     LAST_MODIFIED_DATE DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    #     DELETED_DATE       DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_SUB_TERMS_TERMS FOREIGN KEY (TERMS_ID) REFERENCES TERMS (ID)
);

-- 서브 약관 버전 관리 테이블 (서브 약관의 버전별 내용)
CREATE TABLE SUB_TERMS_VERSION
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '서브 약관 버전 ID (기본 키)',
    SUB_TERMS_ID         BIGINT      NOT NULL COMMENT '서브 약관 ID (외래 키)',
    VERSION_NO           INT         NOT NULL COMMENT '서브 약관 버전 번호',
    CONTENT              TEXT        NOT NULL COMMENT '서브 약관 내용',
    EFFECTIVE_START_DATE DATETIME(6) NOT NULL COMMENT '서브 약관 유효 시작 날짜',
    EFFECTIVE_END_DATE   DATETIME(6) DEFAULT NULL COMMENT '서브 약관 유효 종료 날짜',
    #     CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    #     LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    #     DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_SUB_TERMS_VERSION_SUB_TERMS FOREIGN KEY (SUB_TERMS_ID) REFERENCES SUB_TERMS (ID)
);

-- 회원이 어떤 약관/서브약관을 어느 버전에 동의했는지 기록하는 테이블
CREATE TABLE MEMBER_TERMS_AGREEMENT
(
    ID                          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '멤버 약관 동의 ID (기본 키)',
    MEMBER_ID                   BIGINT NOT NULL COMMENT '회원 ID (외래 키)',
    AGREED_TERMS_VERSION_ID     BIGINT NULL COMMENT '약관 버전 ID (외래 키) - 메인 약관 동의 시',
    AGREED_SUB_TERMS_VERSION_ID BIGINT NULL COMMENT '서브 약관 버전 ID (외래 키) - 서브 약관 동의 시',
    AGREED_DATE                 DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '동의한 날짜',
    #     LAST_MODIFIED_DATE          DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '동의 변경 날짜',
    DELETED_DATE                DATETIME(6) DEFAULT NULL COMMENT '동의 취소 날짜',
    CONSTRAINT FK_MEMBER_TERMS_AGREEMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_TERMS_AGREEMENT_TERMS_VERSION FOREIGN KEY (AGREED_TERMS_VERSION_ID) REFERENCES TERMS_VERSION (ID),
    CONSTRAINT FK_MEMBER_TERMS_AGREEMENT_SUB_TERMS_VERSION FOREIGN KEY (AGREED_SUB_TERMS_VERSION_ID) REFERENCES SUB_TERMS_VERSION (ID)
);