-- =========================================
-- 2. 입고/출고 관련 코드 테이블
-- =========================================
-- 상품 상태코드 테이블
CREATE TABLE PRODUCT_STATUS
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상태코드 ID (기본 키)',
    -- 데이터
    NAME                 VARCHAR(50)  NOT NULL UNIQUE COMMENT '상품 상태 이름 (예: 판매중, 품절 등)',
    DESCRIPTION          VARCHAR(255) NULL COMMENT '상품 상태 코드에 대한 상세 설명으로 상태의 의미와 용도를 설명합니다.',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)'
)
    comment '상품의 상태를 나타내는 테이블';




-- 카테고리 테이블
CREATE TABLE CATEGORY
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '카테고리 ID (기본 키)',

    -- 복합키, 외래키
    PARENT_ID            BIGINT       NULL COMMENT '부모 카테고리 ID (외래 키)',
    SCREEN_ORDER         BIGINT       NOT NULL COMMENT '화면에 보여질 정렬 순서',
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY (ID),
    UNIQUE (PARENT_ID, SCREEN_ORDER),

    -- 데이터
    NAME                 VARCHAR(255) NOT NULL UNIQUE COMMENT '카테고리 이름',
    DESCRIPTION          TEXT         NULL COMMENT '카테고리 설명',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_CATEGORY_LAST_MODIFIED_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- 상품 테이블
CREATE TABLE PRODUCT
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상품 ID (기본 키)',

    -- 외래키
    CATEGORY_ID          BIGINT                NOT NULL COMMENT '카테고리 ID (외래 키)',
    PRODUCT_STATUS_CODE_ID       BIGINT                NOT NULL COMMENT '상품 상태 코드 ID (외래 키)',
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    CONSTRAINT FK_PRODUCT_STATUS FOREIGN KEY (PRODUCT_STATUS_CODE_ID) REFERENCES PRODUCT_STATUS (ID),
    -- 외래키 하나 더 넣기

    -- 데이터
    NAME                 VARCHAR(255)          NOT NULL COMMENT '상품 이름',
    THUMBNAIL_IMAGE      BLOB                  NULL COMMENT '썸네일 이미지',
    SHORT_DESCRIPTION    TEXT                  NULL COMMENT '상품 간단 설명',
    DESCRIPTION_IMAGE    BLOB                  NULL COMMENT '상세 설명 이미지',
    LONG_DESCRIPTION     TEXT                  NULL COMMENT '상품 상세 설명',
    PRICE                INT         DEFAULT 0 NOT NULL COMMENT '판매 가격',

    MANUFACTURER         VARCHAR(255)          NULL COMMENT '제조원',
    EXPIRATION_DATE      DATETIME(6)           NOT NULL COMMENT '소비기한',
    INGREDIENTS          VARCHAR(255)          NULL COMMENT '원재료명 및 성분',
    PRECAUTIONS          VARCHAR(255)          NULL COMMENT '주의사항',
    IMPORTER             VARCHAR(255)          NULL COMMENT '수입원',

    SALE_DATE            DATETIME(6)           NOT NULL COMMENT '판매시작일',

    CAPACITY             INT          NULL COMMENT '용량',
    UNIT                 VARCHAR(255)          NULL COMMENT '단위 (kg, g, ml, ...)',
    QUANTITY             INT          DEFAULT 0 NOT NULL COMMENT '수량',
    CHECK (PRICE >= 0),

    -- 시스템 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    LAST_MODIFIED_MEMBER BIGINT                NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_PRODUCT_LAST_MODIFIED_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT '판매하는 상품의 정보 테이블';

CREATE TABLE STOCK
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '재고 ID (기본 키)',

    -- 외래키
    PRODUCT_ID           BIGINT NOT NULL COMMENT '제품 ID (외래 키)',
    CONSTRAINT FK_PRODUCT_ID_STOCK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),

    -- 데이터
    STOCK_INOUT_QUANTITY BIGINT NOT NULL COMMENT '입출고 수량(입고는 +, 출고는 -)',
    STOCK_INOUT_DATE     DATETIME(6) NOT NULL COMMENT '입출고 날짜',
    CURRENT_STOCK        BIGINT NOT NULL COMMENT '현재 재고 수량(입출고가 발생한 뒤 계산된 값)',
    CHECK ( CURRENT_STOCK >= 0),

    -- 시스템 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    LAST_MODIFIED_MEMBER BIGINT NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_STOCK_LAST_MODIFIED_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT '상품의 재고 정보 테이블';

CREATE TABLE CART
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '장바구니 ID (기본 키)',

    -- 외래키
    MEMBER_ID            BIGINT                                   NOT NULL COMMENT '회원 ID (외래 키)',
    PRODUCT_ID           BIGINT                                   NOT NULL COMMENT '상품 ID (외래 키)',
    CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    QUANTITY             BIGINT      DEFAULT 1                    NOT NULL COMMENT '상품별 주문 수량',
    PICKED_DATE          DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL COMMENT '장바구니에 담은 날짜',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT                                   NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_CART_LAST_MODIFIED_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
);