-- =========================================
-- 2. 입고/출고 관련 코드 테이블
-- =========================================

-- 카테고리 테이블
CREATE TABLE CATEGORY
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '카테고리 ID (기본 키)',
    NAME               VARCHAR(255) NOT NULL UNIQUE COMMENT '카테고리 이름',
    PARENT_ID          BIGINT       NULL COMMENT '부모 카테고리 ID (외래 키)',
    SCREEN_ORDER       BIGINT       NOT NULL COMMENT '화면에 보여질 정렬 순서',
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY (ID)
);

-- 상품 테이블
CREATE TABLE PRODUCT
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상품 ID (기본 키)',
    NAME               VARCHAR(255)          NOT NULL COMMENT '상품 이름',
    SHORT_DESCRIPTION  TEXT                  NULL COMMENT '상품 간단 설명',
    LONG_DESCRIPTION   TEXT                  NULL COMMENT '상품 상세 설명',
    MAIN_DESCRIPTION   VARCHAR(1000)         NULL COMMENT '상품 본문 내용',
    PRICE              INT         DEFAULT 0 NOT NULL COMMENT '판매 가격',
    CATEGORY_ID        BIGINT                NOT NULL COMMENT '카테고리 ID (외래 키)',
    IMPORTER           VARCHAR(255)          NULL COMMENT '수입원',
    MANUFACTURER       VARCHAR(255)          NULL COMMENT '제조원',
    EXPIRATION_DATE    DATETIME(6)           NOT NULL COMMENT '소비기한',
    SIZE               VARCHAR(255)          NULL COMMENT '사이즈',
    CAPACITY           VARCHAR(255)          NULL COMMENT '용량(수량)',
    INGREDIENTS        VARCHAR(255)          NULL COMMENT '원재료명 및 성분',
    PRECAUTIONS        VARCHAR(255)          NULL COMMENT '주의사항',
    SALE_DATE          DATETIME(6)           NOT NULL COMMENT '판매시작일',
    REGISTRATION_DATE  DATETIME(6)           NOT NULL COMMENT '상품등록일',
    NEW                BOOLEAN     DEFAULT FALSE COMMENT '신상품',
    HOT                BOOLEAN     DEFAULT FALSE COMMENT '최근 인기 상품',
    BEST               BOOLEAN     DEFAULT FALSE COMMENT '인기 상품',
    COMMON_CODE_ID     BIGINT       NOT NULL COMMENT '공통 코드 ID (외래 키)',
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CHECK (PRICE >= 0),
    CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID),
    CONSTRAINT FK_PRODUCT_COMMON_CODE FOREIGN KEY (COMMON_CODE_ID) REFERENCES COMMON_CODE (ID)
);

-- 상품 이력 테이블
CREATE TABLE PRODUCT_HISTORY
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '상품 이력 ID (기본 키)',
    PRODUCT_ID           BIGINT       NOT NULL COMMENT '원래 상품 ID (외래 키)',
#     NAME                 VARCHAR(255) NOT NULL COMMENT '상품 이름(이전)',
#     DESCRIPTION          TEXT         NULL COMMENT '상품 설명(이전)',
    PRICE                INT          NOT NULL COMMENT '판매 가격(이전)',
    CATEGORY_ID          BIGINT       NOT NULL COMMENT '카테고리 ID(이전)',
    OPERATION_TYPE       VARCHAR(10)  NOT NULL COMMENT '조작 유형(UPDATE/DELETE)',
    HISTORY_CREATED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '이력 생성 날짜',
    CREATED_DATE         DATETIME(6)  NULL COMMENT '제품 원래 생성 날짜(이전)',
    LAST_MODIFIED_DATE   DATETIME(6)  NULL COMMENT '제품 원래 수정 날짜(이전)',
    DELETED_DATE         DATETIME(6)  NULL COMMENT '제품 원래 삭제 날짜(이전)',
    CONSTRAINT FK_PRODUCT_HISTORY_PRODUCT
        FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE
);

-- 가격 이력 테이블
CREATE TABLE PRICE_HISTORY
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '가격 이력 ID (기본 키)',
    PRODUCT_ID         BIGINT      NOT NULL COMMENT '원래 상품 ID(외래 키)',
    PRICE              INT         NOT NULL COMMENT '할인 가격',
    CHANGE_START_DATE  DATETIME(6) NULL COMMENT '변경 시작 일자',
    CHANGE_END_DATE    DATETIME(6) NULL COMMENT '변경 종료 일자',
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);
-- 입고 코드 테이블
CREATE TABLE INBOUND_CODE
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '입고 코드 ID (기본 키)',

    -- 데이터
    NAME               VARCHAR(255) NOT NULL UNIQUE COMMENT '입고 코드 이름',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '입고 코드 설명',

    -- 시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

-- 출고 코드 테이블
# CREATE TABLE OUTBOUND_CODE
# (
#     -- 기본키
#     ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '출고 코드 ID (기본 키)',
#
#     -- 데이터
#     NAME               VARCHAR(255) NOT NULL UNIQUE COMMENT '출고 코드 이름',
#     DESCRIPTION        VARCHAR(255) NULL COMMENT '출고 코드 설명',
#
#     -- 시스템 컬럼
#     CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
#     LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
#     DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
# );

-- 발주 테이블
CREATE TABLE INBOUND_ORDER
(
    ID                      BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '발주 ID (기본 키)',
    ORDER_DATE              DATETIME(6) NOT NULL COMMENT '발주 날짜',
    EXPECTED_INBOUND_DATE   DATETIME(6) NOT NULL COMMENT '예상 입고 날짜',
    STATUS                  VARCHAR(10) NOT NULL COMMENT '발주 상태',
    TOTAL_QUANTITY          BIGINT      NOT NULL COMMENT '총 발주 수량',
    TOTAL_AMOUNT            BIGINT      NOT NULL COMMENT '총 발주 금액',
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

-- 입고 메인 테이블
CREATE TABLE INBOUND_MAIN
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '입고 메인 ID (기본 키)',

    -- 외래키
    INBOUND_ORDER_ID   BIGINT NOT NULL COMMENT '발주 ID (외래 키)',
    CONSTRAINT FK_INBOUND_MAIN_ORDER FOREIGN KEY (INBOUND_ORDER_ID) REFERENCES INBOUND_ORDER (ID) ON DELETE CASCADE,

        -- 데이터
    RECEIVED_DATE      DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL COMMENT '입고 날짜',

    -- 시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

-- 입고 상세 테이블
CREATE TABLE INBOUND_DETAIL
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '입고 디테일 ID (기본 키)',

    -- 외래키
    INBOUND_MAIN_ID    BIGINT       NOT NULL COMMENT '입고 메인 ID (외래 키)',
    PRODUCT_ID         BIGINT       NOT NULL COMMENT '제품 ID (외래 키)',
    BATCH_NUMBER       VARCHAR(255) NOT NULL COMMENT '배치 번호',
    COMMON_CODE_ID     BIGINT       NOT NULL COMMENT '공통 코드 ID (외래 키)',
    CONSTRAINT FK_INBOUND_DETAIL_MAIN FOREIGN KEY (INBOUND_MAIN_ID) REFERENCES INBOUND_MAIN (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_INBOUND_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_INBOUND_DETAIL_INBOUND FOREIGN KEY (COMMON_CODE_ID) REFERENCES COMMON_CODE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    QUANTITY           INT          NOT NULL COMMENT '입고 수량',
    PRICE              INT          NOT NULL COMMENT '입고 가격',
    EXPIRY_DATE        DATETIME(6)  NOT NULL COMMENT '유통기한',
    INBOUND_LOCATION   VARCHAR(255) NULL COMMENT '입고 위치',
    CHECK (QUANTITY > 0),

    -- 시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

-- 출고 메인 테이블
CREATE TABLE OUTBOUND_MAIN
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '출고 메인 ID (기본 키)',

    -- 데이터
    OUTBOUND_DATE      DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL COMMENT '출고 날짜',

    -- 시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

CREATE TABLE OUTBOUND_DETAIL
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '출고 디테일 ID (기본 키)',

    -- 외래키
    OUTBOUND_MAIN_ID   BIGINT  NOT NULL COMMENT '출고 메인 ID (외래 키)',
    INBOUND_DETAIL_ID  BIGINT  NOT NULL COMMENT '입고 디테일 ID (외래 키)',
    OUTBOUND_CODE_ID   BIGINT  NOT NULL COMMENT '출고 코드 ID (외래 키)',
    CONSTRAINT FK_OUTBOUND_DETAIL_MAIN FOREIGN KEY (OUTBOUND_MAIN_ID) REFERENCES OUTBOUND_MAIN (ID) ON DELETE CASCADE,
    CONSTRAINT FK_OUTBOUND_DETAIL_INBOUND FOREIGN KEY (INBOUND_DETAIL_ID) REFERENCES INBOUND_DETAIL (ID) ON DELETE CASCADE,
    CONSTRAINT FK_OUTBOUND_DETAIL_OUTBOUND FOREIGN KEY (OUTBOUND_CODE_ID) REFERENCES OUTBOUND_CODE (ID) ON DELETE CASCADE,

    -- 데이터
    QUANTITY           INT     NOT NULL COMMENT '출고 수량',
    IS_PROCESSED       BOOLEAN NOT NULL COMMENT '처리 여부',
    CHECK (QUANTITY > 0),

    -- 시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

-- 재고 테이블
CREATE TABLE STOCK
(
    -- 기본키
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '재고 ID (기본 키)',

    -- 외래키
    PRODUCT_ID         BIGINT       NOT NULL COMMENT '제품 ID (외래 키)',
    CONSTRAINT FK_PRODUCT_ID_STOCK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),

    -- 데이터
    CURRENT_STOCK      BIGINT       NOT NULL COMMENT '현재 재고 수량',
    BATCH_NUMBER       VARCHAR(255) NOT NULL COMMENT '배치 번호',

    -- 시스템 컬럼
    CREATED_DATE       DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜'
);

CREATE TABLE CART
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '장바구니 ID (기본 키)',

    -- 외래키
    MEMBER_ID            BIGINT                                   NOT NULL COMMENT '회원 ID (외래 키)',
    PRODUCT_ID           BIGINT                                   NOT NULL COMMENT '상품 ID (외래 키)',
    CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    ORDER_QUANTITY       BIGINT      DEFAULT 1                    NOT NULL COMMENT '상품별 주문 수량',
    ADDED_DATE           DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL COMMENT '장바구니에 담은 날짜',

    -- 시스템 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NULL COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NULL ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE         DATETIME(6) DEFAULT NULL                 NULL COMMENT '삭제 날짜'
);