-- =========================================
-- 3. 주문/결제 관련 코드 테이블
-- =========================================

-- =========================================
-- 코드 테이블
-- =========================================

CREATE TABLE ORDER_STATUS_CODE
(
    --  기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 상태 코드의 고유 ID (기본 키)',

    -- 데이터
    NAME                 VARCHAR(50)  NOT NULL UNIQUE COMMENT '주문 상태 이름 (예: 결제 완료, 배송 준비 등)',
    DESCRIPTION          VARCHAR(255) NULL COMMENT '주문 상태 코드에 대한 상세 설명으로, 상태의 의미와 용도를 설명합니다.',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_STATUS_CODE_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문 상태 코드를 저장하며, 주문의 현재 상태를 관리하는 테이블입니다. 예를 들어 결제 완료, 배송 준비 등의 상태를 포함합니다.';

CREATE TABLE DELIVERY_STATUS_CODE
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '배송 상태 코드의 고유 ID (기본 키)',

    -- 데이터
    NAME                 VARCHAR(50)  NOT NULL UNIQUE COMMENT '배송 상태 이름 (예: 배송 준비, 배송 중, 배송 완료 등)',
    DESCRIPTION          VARCHAR(255) NULL COMMENT '배송 상태 코드에 대한 상세 설명으로, 상태의 의미와 사용 목적을 설명합니다.',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_DELIVERY_STATUS_CODE_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '배송 상태 코드를 저장하며, 배송의 현재 상태를 관리하는 테이블입니다. 예를 들어 배송 준비, 배송 중, 배송 완료 등의 상태를 포함합니다.';

CREATE TABLE PAYMENT_METHOD_CODE
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '결제 코드 ID (기본 키)',

    -- 데이터
    NAME                 VARCHAR(50)  NOT NULL UNIQUE COMMENT '결제 코드 이름',
    DESCRIPTION          VARCHAR(255) NULL COMMENT '결제 코드 설명',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_PAYMENT_METHOD_CODE_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
);


CREATE TABLE PAYMENT_STATUS_CODE
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '결제 상태 코드의 고유 ID (기본 키)',

    -- 데이터
    NAME                 VARCHAR(50)  NOT NULL UNIQUE COMMENT '결제 상태 이름 (예: 결제 완료, 결제 취소 등)',
    DESCRIPTION          VARCHAR(255) NULL COMMENT '결제 상태 코드에 대한 상세 설명으로, 상태의 의미와 사용 목적을 설명합니다.',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_PAYMENT_STATUS_CODE_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문 상태 코드를 저장하며, 주문의 현재 상태를 관리하는 테이블입니다. 예를 들어 결제 완료, 배송 준비 등의 상태를 포함합니다.';
#
#
-- =========================================
-- 주문
-- =========================================

CREATE TABLE ORDER_MAIN
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 고유 ID (기본 키)',

    -- 외래키
    MEMBER_ID            BIGINT                                   NOT NULL COMMENT '주문을 생성한 회원의 고유 ID (외래 키)',
    CONSTRAINT FK_ORDER_MAIN_MEMBER2 FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    ORDER_DATE           DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL COMMENT '주문이 발생한 날짜 및 시간',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT                                   NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_MAIN_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '회원의 주문 정보를 저장하는 메인 테이블로, 주문의 기본 정보(총 금액, 주문 날짜 등)를 관리합니다.';

CREATE TABLE ORDER_DETAIL
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 상세 고유 ID (기본 키)',

    -- 유니크키
    ORDER_ID             BIGINT NOT NULL COMMENT '주문 ID',
    PRODUCT_ID           BIGINT NOT NULL COMMENT '제품 ID',
    UNIQUE KEY (ORDER_ID, PRODUCT_ID),
    CONSTRAINT FK_ORDER_DETAIL_MAIN FOREIGN KEY (ORDER_ID) REFERENCES ORDER_MAIN (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    QUANTITY               INT    NOT NULL COMMENT '구매 수량',
    UNIT_PRICE             INT    NOT NULL COMMENT '제품 단가',
    CHECK ( QUANTITY > 0 ),
    CHECK ( UNIT_PRICE >= 0 ),

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_DETAIL_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문 상세 정보를 저장하는 테이블로, 각 주문에 포함된 제품과 그 수량을 관리합니다.';

CREATE TABLE ORDER_DETAIL_STATUS
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 상태 변경 이력 고유 ID (기본 키)',

    -- 유니크 키
    ORDER_DETAIL_ID      BIGINT NOT NULL COMMENT '주문 상세 ID',
    ORDER_STATUS_CODE_ID BIGINT NOT NULL COMMENT '주문 상태 코드 ID',
    UNIQUE KEY (ORDER_DETAIL_ID, ORDER_STATUS_CODE_ID),
    CONSTRAINT FK_ORDER_DETAIL_STATUS_DETAIL FOREIGN KEY (ORDER_DETAIL_ID) REFERENCES ORDER_DETAIL (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_ORDER_DETAIL_STATUS_CODE FOREIGN KEY (ORDER_STATUS_CODE_ID) REFERENCES ORDER_STATUS_CODE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    ORDER_DATE           DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '주문 상태 변경 날짜 및 시간',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_DETAIL_STATUS_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문의 상태 변경 이력을 저장하는 테이블로, 각 주문의 상태 변화를 추적합니다.';

CREATE TABLE ORDER_DELIVERY_MAIN
(
    -- 기본키
    ID                    BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 배송 고유 ID (기본 키)',

    -- 외래키
    ORDER_MAIN_ID         BIGINT       NOT NULL COMMENT '주문 ID',
    CONSTRAINT FK_ORDER_DELIVERY_MAIN_ORDER FOREIGN KEY (ORDER_MAIN_ID) REFERENCES ORDER_MAIN (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    DELIVERY_COMPANY_NAME VARCHAR(50)  NOT NULL COMMENT '배송 업체 이름',
    TRACKING_NUMBER       VARCHAR(50)  NOT NULL COMMENT '송장 번호',
    DELIVERY_REQUEST_NOTE VARCHAR(255) NULL COMMENT '배송 요청 사항',

    -- 시스템 관리 컬럼
    CREATED_DATE          DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE    DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER  BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE          DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_DELIVERY_MAIN_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT

)
    COMMENT = '주문의 배송 정보를 저장하는 테이블로, 주문의 배송 정보를 관리합니다.';

CREATE TABLE ORDER_DELIVERY_STATUS
(
    -- 기본키
    ID                      BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 배송 상태 변경 이력 고유 ID (기본 키)',

    --  유니크 외래키
    ORDER_DELIVERY_MAIN_ID  BIGINT NOT NULL COMMENT '주문 배송 ID',
    DELIVERY_STATUS_CODE_ID BIGINT NOT NULL COMMENT '배송 상태 코드 ID',
    UNIQUE KEY (ORDER_DELIVERY_MAIN_ID, DELIVERY_STATUS_CODE_ID),
    CONSTRAINT FK_ORDER_DELIVERY_STATUS_MAIN FOREIGN KEY (ORDER_DELIVERY_MAIN_ID) REFERENCES ORDER_DELIVERY_MAIN (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_ORDER_DELIVERY_STATUS_CODE FOREIGN KEY (DELIVERY_STATUS_CODE_ID) REFERENCES DELIVERY_STATUS_CODE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터 컬럼
    DELIVERY_DATE           DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '배송 상태 변경 시간, 예, 배송 출발 시간, 배송 완료 시간',

    -- 시스템 관리 컬럼
    CREATED_DATE            DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE      DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER    BIGINT NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE            DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_DELIVERY_STATUS_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문의 배송 상태 변경 이력을 저장하는 테이블로, 각 주문의 배송 상태 변화를 추적합니다.';

CREATE TABLE ORDER_PAYMENT_MAIN
(
    -- 기본키
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '주문 결제 고유 ID (기본 키)',

    -- 외래키
    ORDER_ID             BIGINT NOT NULL COMMENT '주문 ID',
    CONSTRAINT FK_ORDER_PAYMENT_MAIN_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDER_MAIN (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 데이터
    TOTAL_AMOUNT         INT    NOT NULL COMMENT '총 결제 금액',

    -- 시스템 관리 컬럼
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER BIGINT NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_PAYMENT_MAIN_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문의 결제 정보를 저장하는 테이블로, 주문의 결제 방법과 결제 금액을 관리합니다.';

CREATE TABLE ORDER_PAYMENT_DETAIL
(
    -- 기본키
    ORDER_PAYMENT_MAIN_ID        BIGINT AUTO_INCREMENT COMMENT '주문 결제 상세 고유 ID (기본 키)',
    PAYMENT_METHOD_CODE_ID       BIGINT       NOT NULL COMMENT '결제 방법 코드 ID',
    ORDER_PAYMENT_STATUS_CODE_ID BIGINT       NOT NULL COMMENT '주문 결제 상태 코드 ID',
    PRIMARY KEY (ORDER_PAYMENT_MAIN_ID, PAYMENT_METHOD_CODE_ID, ORDER_PAYMENT_STATUS_CODE_ID),
    CONSTRAINT FK_ORDER_PAYMENT_DETAIL_MAIN FOREIGN KEY (ORDER_PAYMENT_MAIN_ID) REFERENCES ORDER_PAYMENT_MAIN (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_ORDER_PAYMENT_DETAIL_METHOD FOREIGN KEY (PAYMENT_METHOD_CODE_ID) REFERENCES PAYMENT_METHOD_CODE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_ORDER_PAYMENT_DETAIL_STATUS FOREIGN KEY (ORDER_PAYMENT_STATUS_CODE_ID) REFERENCES PAYMENT_STATUS_CODE (ID) ON UPDATE CASCADE ON DELETE RESTRICT,

    -- 대체키
    APPROVAL_NUMBER             VARCHAR(50)  NULL COMMENT '승인 번호',

    -- 데이터

    PAYMENT_AMOUNT               INT          NOT NULL COMMENT '결제 금액',
    PAYMENT_DATE                 DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '결제 날짜 및 시간',
    PAYMENT_COMMENT              VARCHAR(255) NULL COMMENT '결제에 대한 추가 설명',

    -- 시스템 관리 컬럼
    CREATED_DATE                 DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '레코드 생성 날짜 및 시간',
    LAST_MODIFIED_DATE           DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '마지막 수정된 날짜 및 시간',
    LAST_MODIFIED_MEMBER         BIGINT       NULL COMMENT '레코드를 마지막으로 수정한 회원 ID',
    DELETED_DATE                 DATETIME(6) DEFAULT NULL COMMENT '레코드가 삭제된 날짜 (논리 삭제)',
    CONSTRAINT FK_ORDER_PAYMENT_DETAIL_MEMBER FOREIGN KEY (LAST_MODIFIED_MEMBER) REFERENCES MEMBER (ID) ON UPDATE CASCADE ON DELETE RESTRICT
)
    COMMENT = '주문의 결제 상세 정보를 저장하는 테이블로, 각 주문의 결제 금액과 결제 날짜를 관리합니다.';
