-- =========================================
-- 5. 포인트 및 정책 관련 코드 테이블
-- =========================================

-- 약관 메인 테이블 (약관 종류 정의)
CREATE TABLE TERMS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '약관 ID (기본 키)',
    NAME               VARCHAR(100) NOT NULL UNIQUE COMMENT '약관 이름 (예: 이용약관, 개인정보처리방침 등)',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '약관 설명',
    REQUIRED           BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '필수 동의 여부',
    ACTIVATED          BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '약관 활성화 여부',
    CREATED_DATE       DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜'
);

-- 약관 버전 관리 테이블 (메인 약관의 버전별 내용)
CREATE TABLE TERMS_VERSION
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '약관 버전 ID (기본 키)',

    TERMS_ID             BIGINT      NOT NULL COMMENT '약관 ID (외래 키)',
    VERSION_NO           INT         NOT NULL COMMENT '약관 버전 번호',
    CONTENT              TEXT        NOT NULL COMMENT '약관 내용',
    EFFECTIVE_START_DATE DATETIME(6) NOT NULL COMMENT '약관 유효 시작 날짜',
    EFFECTIVE_END_DATE   DATETIME(6) DEFAULT NULL COMMENT '약관 유효 종료 날짜',
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_TERMS_VERSION_TERMS FOREIGN KEY (TERMS_ID) REFERENCES TERMS (ID)
);

-- 서브 약관 테이블 (메인 약관 하위에 속하는 세부 약관 정의)
CREATE TABLE SUB_TERMS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '서브 약관 ID (기본 키)',
    TERMS_ID           BIGINT       NOT NULL COMMENT '메인 약관 ID (외래 키)',
    NAME               VARCHAR(100) NOT NULL COMMENT '서브 약관 이름 (예: 개인정보 이용동의, 위치정보 이용동의 등)',
    DESCRIPTION        VARCHAR(255) NULL COMMENT '서브 약관 설명',
    REQUIRED           BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '필수 동의 여부',
    ACTIVATED          BOOLEAN      NOT NULL DEFAULT TRUE COMMENT '약관 활성화 여부',
    CREATED_DATE       DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE DATETIME(6)           DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE       DATETIME(6)           DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_SUB_TERMS_TERMS FOREIGN KEY (TERMS_ID) REFERENCES TERMS (ID)
);

-- 서브 약관 버전 관리 테이블 (서브 약관의 버전별 내용)
CREATE TABLE SUB_TERMS_VERSION
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '서브 약관 버전 ID (기본 키)',
    SUB_TERMS_ID         BIGINT      NOT NULL COMMENT '서브 약관 ID (외래 키)',
    VERSION_NO           INT         NOT NULL COMMENT '서브 약관 버전 번호',
    CONTENT              TEXT        NOT NULL COMMENT '서브 약관 내용',
    EFFECTIVE_START_DATE DATETIME(6) NOT NULL COMMENT '서브 약관 유효 시작 날짜',
    EFFECTIVE_END_DATE   DATETIME(6) DEFAULT NULL COMMENT '서브 약관 유효 종료 날짜',
    CREATED_DATE         DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 날짜',
    LAST_MODIFIED_DATE   DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 날짜',
    DELETED_DATE         DATETIME(6) DEFAULT NULL COMMENT '삭제 날짜',
    CONSTRAINT FK_SUB_TERMS_VERSION_SUB_TERMS FOREIGN KEY (SUB_TERMS_ID) REFERENCES SUB_TERMS (ID)
);

-- 회원이 어떤 약관/서브약관을 어느 버전에 동의했는지 기록하는 테이블
CREATE TABLE MEMBER_TERMS_AGREEMENT
(
    ID                          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '멤버 약관 동의 ID (기본 키)',
    MEMBER_ID                   BIGINT NOT NULL COMMENT '회원 ID (외래 키)',
    AGREED_TERMS_VERSION_ID     BIGINT NULL COMMENT '약관 버전 ID (외래 키) - 메인 약관 동의 시',
    AGREED_SUB_TERMS_VERSION_ID BIGINT NULL COMMENT '서브 약관 버전 ID (외래 키) - 서브 약관 동의 시',
    AGREED_DATE                 DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT '동의한 날짜',
    LAST_MODIFIED_DATE          DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '동의 변경 날짜',
    DELETED_DATE                DATETIME(6) DEFAULT NULL COMMENT '동의 취소 날짜',
    CONSTRAINT FK_MEMBER_TERMS_AGREEMENT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_MEMBER_TERMS_AGREEMENT_TERMS_VERSION FOREIGN KEY (AGREED_TERMS_VERSION_ID) REFERENCES TERMS_VERSION (ID),
    CONSTRAINT FK_MEMBER_TERMS_AGREEMENT_SUB_TERMS_VERSION FOREIGN KEY (AGREED_SUB_TERMS_VERSION_ID) REFERENCES SUB_TERMS_VERSION (ID)
);
